### ISSUE TITLE
Session Replays on Android not recording/logging requests

### ISSUE THREAD

**Issue by jrusso1020** [PostHog/posthog-react-native-session-replay#18]
We had a very similar issue for iOS that was fixed by the team https://github.com/PostHog/posthog-js-lite/issues/276

The previous issue includes info on our app setup and how we make requests

The setup is exactly the same although our package versions are different now

```
posthogInstance = new PostHog(config.posthog.apiKey, {
    host: 'https://us.i.posthog.com',
    disableGeoip: true,
    // Comment out the line below to enable PostHog in dev
    disabled: __DEV__ || !config.posthog.enabled, // Disable in dev or if not enabled in config
    enableSessionReplay: true,
  });
```

### Package Versions
expo@npm:51.0.39 (via npm:~51.0.39)
posthog-react-native@npm:3.3.9 [2f28e] (via npm:^3.3.9 [2f28e])
posthog-react-native-session-replay@npm:0.1.6 [2f28e] (via npm:^0.1.6 [2f28e])
react-native@npm:0.74.5 [2f28e] (via npm:0.74.5 [2f28e])

**Comment by marandaneto** [comment]
It is iOS only for now https://posthog.com/docs/session-replay/network-recording?tab=React+Native
You cannot "monkeypatch" the Android bits at runtime, only with bytecode manipulation.
+1 on https://github.com/PostHog/posthog-js-lite/issues/310 please so we can prioritize.
